fix patches/do-not-hide-test-output.diff and re-enable

diff --git a/patches/do-not-hide-test-output.diff b/patches/do-not-hide-test-output.diff
--- a/patches/do-not-hide-test-output.diff
+++ b/patches/do-not-hide-test-output.diff
@@ -1,95 +1,80 @@
-diff --git a/config_host.mk.in b/config_host.mk.in
-index 4a864c745424..a311e6044650 100644
---- a/config_host.mk.in
-+++ b/config_host.mk.in
-@@ -12,6 +12,8 @@ gb_SPACE:=$(gb_SPACE) $(gb_SPACE)
- export SRC_ROOT=@SRC_ROOT@
- export BUILDDIR=@BUILDDIR@
- 
-+export SHELL=/bin/bash
-+
- @x_AFLAGS@ export AFLAGS=@AFLAGS@
- export ABW_CFLAGS=$(gb_SPACE)@ABW_CFLAGS@
- export ABW_LIBS=$(gb_SPACE)@ABW_LIBS@
 diff --git a/odk/build-examples_common.mk b/odk/build-examples_common.mk
-index 931d6eea856e..11772caf0ffe 100644
+index 931d6eea856e..5ea56e959bfc 100644
 --- a/odk/build-examples_common.mk
 +++ b/odk/build-examples_common.mk
-@@ -26,13 +26,13 @@ endif
- 	(saved_library_path=$$$${$(gb_Helper_LIBRARY_PATH_VAR)} && . $$< \
- 	$(if $(filter MACOSX,$(OS)),, \
- 	    && $(gb_Helper_LIBRARY_PATH_VAR)=$$$$saved_library_path) \
--	&& export \
-+	&& set -o pipefail; export \
- 	    UserInstallation=$(call gb_Helper_make_url,$(call gb_CustomTarget_get_workdir,$(1))/user) \
- 	$(foreach my_dir,$(2), \
+@@ -32,11 +32,7 @@ endif
  	    && (cd $(INSTDIR)/$(SDKDIRNAME)/examples/$(my_dir) \
  		&& printf 'yes\n' | LC_ALL=C make \
  		    $(if $(filter MACOSX,$(OS)), SHELL=$(ODK_BUILD_SHELL), )))) \
 -	    >$(call gb_CustomTarget_get_workdir,$(1))/log 2>&1 \
-+	    2>&1 | tee $(call gb_CustomTarget_get_workdir,$(1))/log \
- 	|| (RET=$$$$? \
- 	    $(if $(filter MACOSX,$(OS)), && rm -f $(ODK_BUILD_SHELL) , ) \
- 	    && cat $(call gb_CustomTarget_get_workdir,$(1))/log \
+-	|| (RET=$$$$? \
+-	    $(if $(filter MACOSX,$(OS)), && rm -f $(ODK_BUILD_SHELL) , ) \
+-	    && cat $(call gb_CustomTarget_get_workdir,$(1))/log \
+-	    && exit $$$$RET)
++	    2>&1
+ ifeq (MACOSX,$(OS))
+ 	-rm -f $(ODK_BUILD_SHELL)
+ endif
 diff --git a/solenv/gbuild/CppunitTest.mk b/solenv/gbuild/CppunitTest.mk
-index 45af5c9b25a7..1f60573cf7c4 100644
+index 45af5c9b25a7..7933fc84c8b2 100644
 --- a/solenv/gbuild/CppunitTest.mk
 +++ b/solenv/gbuild/CppunitTest.mk
-@@ -122,7 +122,7 @@ else
- 		$(if $(gb_CppunitTest__interactive),, \
- 			$(if $(value gb_CppunitTest_postprocess), \
- 				rm -fr $@.core && mkdir $@.core && cd $@.core &&)) \
--		( \
-+		( set -o pipefail; \
- 		$(if $(gb_CppunitTest_localized),for l in $(WITH_LANG_LIST) ; do LO_TEST_LOCALE="$$l" ) \
- 		$(if $(gb_CppunitTest_PREGDBTRACE),$(gb_CppunitTest_PREGDBTRACE) &&) \
- 		$(EXTRA_ENV_VARS) \
-@@ -140,7 +140,7 @@ else
+@@ -139,12 +139,7 @@ else
+ 			; RET=$$? && $(gb_CppunitTest_POSTGDBTRACE) && (exit $$RET)) \
  		$(if $(gb_CppunitTest_localized),|| exit $$?; done) \
  		) \
- 		$(if $(gb_CppunitTest__interactive),, \
+-		$(if $(gb_CppunitTest__interactive),, \
 -			> $@.log 2>&1 \
-+			2>&1 | tee $@.log \
- 			|| ($(if $(value gb_CppunitTest_postprocess), \
- 					RET=$$?; \
- 					$(call gb_CppunitTest_postprocess,$(gb_CppunitTest_CPPTESTCOMMAND),$@.core,$$RET) >> $@.log 2>&1;) \
+-			|| ($(if $(value gb_CppunitTest_postprocess), \
+-					RET=$$?; \
+-					$(call gb_CppunitTest_postprocess,$(gb_CppunitTest_CPPTESTCOMMAND),$@.core,$$RET) >> $@.log 2>&1;) \
+-				cat $@.log; $(gb_CppunitTest_UNITTESTFAILED) Cppunit $*)))
++		2>&1)
+ endif
+ 
+ define gb_CppunitTest_CppunitTest
 diff --git a/solenv/gbuild/JunitTest.mk b/solenv/gbuild/JunitTest.mk
-index 36f29b50ef28..a770f81cce60 100644
+index 36f29b50ef28..3ac4603ff6a0 100644
 --- a/solenv/gbuild/JunitTest.mk
 +++ b/solenv/gbuild/JunitTest.mk
-@@ -40,11 +40,11 @@ else
-         rm -rf $(call gb_JunitTest_get_userdir,$*) && \
- 		mkdir -p $(call gb_JunitTest_get_userdir,$*)/user && \
- 		cp $(SRCDIR)/qadevOOo/qa/registrymodifications.xcu $(call gb_JunitTest_get_userdir,$*)/user/ && \
--        ($(gb_JunitTest_JAVACOMMAND) \
-+        (set -o pipefail; $(gb_JunitTest_JAVACOMMAND) \
+@@ -44,17 +44,7 @@ else
              -classpath "$(T_CP)" \
              $(DEFS) \
              org.junit.runner.JUnitCore \
 -            $(CLASSES) > $@.log 2>&1 || \
-+            $(CLASSES) 2>&1 | tee $@.log || \
- 		(cat $@.log \
- 		&& echo "to rerun just this failed test without all others, run:" \
- 		&& echo && echo "    make JunitTest_$*" && echo \
+-		(cat $@.log \
+-		&& echo "to rerun just this failed test without all others, run:" \
+-		&& echo && echo "    make JunitTest_$*" && echo \
+-		&& echo "cd into the module dir to run the tests faster" \
+-		&& echo "Or to do interactive debugging, run two shells with:" \
+-		&& echo \
+-		&& echo "    make debugrun" \
+-		&& echo "    make gb_JunitTest_DEBUGRUN=T JunitTest_$*" \
+-		&& echo \
+-		&& false)))
++            $(CLASSES) 2>&1))
+ 	$(CLEAN_CMD)
+ endif
+ 
 diff --git a/solenv/gbuild/UITest.mk b/solenv/gbuild/UITest.mk
-index 03d30448ef7b..87e4d56a0d9c 100644
+index 03d30448ef7b..5628e47866f8 100644
 --- a/solenv/gbuild/UITest.mk
 +++ b/solenv/gbuild/UITest.mk
-@@ -59,7 +59,7 @@ else
- 		    rm -fr $@.core && mkdir -p $(dir $(call gb_UITest_get_target,$*))user/ && mkdir $@.core && cd $@.core && ) \
- 		$(if $(gb_UITest_use_config), \
- 		    cp $(gb_UITest_use_config) $(dir $(call gb_UITest_get_target,$*))user/. && ) \
--		($(gb_UITest_PRECOMMAND) \
-+		(set -o pipefail; $(gb_UITest_PRECOMMAND) \
- 		$(if $(G_SLICE),G_SLICE=$(G_SLICE)) \
- 		$(if $(GLIBCXX_FORCE_NEW),GLIBCXX_FORCE_NEW=$(GLIBCXX_FORCE_NEW)) \
- 		$(DEFS) \
-@@ -78,7 +78,7 @@ else
+@@ -77,16 +77,7 @@ else
+ 		--userdir=$(call gb_Helper_make_url,$(dir $(call gb_UITest_get_target,$*))user) \
  		--dir=$(strip $(MODULES)) \
  		$(gb_UITest_GDBTRACE) \
- 		$(if $(gb_UITest__interactive),, \
+-		$(if $(gb_UITest__interactive),, \
 -		    > $@.log 2>&1 \
-+		    2>&1 | tee $@.log \
- 		    || ($(if $(value gb_CppunitTest_postprocess), \
- 				    RET=$$?; \
- 				    $(call gb_CppunitTest_postprocess,$(gb_UITest_EXECUTABLE_GDB),$@.core,$$RET) >> $@.log 2>&1;) \
+-		    || ($(if $(value gb_CppunitTest_postprocess), \
+-				    RET=$$?; \
+-				    $(call gb_CppunitTest_postprocess,$(gb_UITest_EXECUTABLE_GDB),$@.core,$$RET) >> $@.log 2>&1;) \
+-                $(if $(filter WNT,$(OS)), \
+-                    printf '%s: <<<\n' $(dir $(call gb_UITest_get_target,$*))/soffice.out.log; \
+-                    cat $(dir $(call gb_UITest_get_target,$*))/soffice.out.log; \
+-                    printf ' >>>\n\n';) \
+-			    cat $@.log; $(gb_UITest_UNITTESTFAILED) UI $*))))
++		2>&1))
+ endif
+ 
+ # always use udkapi and URE services
