lp#916291: soft fail on registering extensions

diff --git a/libreoffice-common.postinst.in b/libreoffice-common.postinst.in
--- a/libreoffice-common.postinst.in
+++ b/libreoffice-common.postinst.in
@@ -18,7 +18,7 @@ if [ "$1" = "configure" ]; then
 	rmdir /etc/openoffice 2>/dev/null || true
 
 	if dpkg --compare-versions "$2" lt "1:3.3.0-3"; then
-		dpkg-trigger /@OODIR@/share/extensions
+		dpkg-trigger /@OODIR@/share/extensions || (echo "failed to trigger extension registration" && true)
 	fi
 fi
 
