try to rmdir /etc/libreoffice/registry/res/

diff --git a/libreoffice-l10n.preinst.in b/libreoffice-l10n.preinst.in
--- a/libreoffice-l10n.preinst.in
+++ b/libreoffice-l10n.preinst.in
@@ -26,4 +26,13 @@ elif [ "$1" = "install" ] && [ -f /etc/libreoffice/registry/Langpack-@ISO@.xcd ]
 	done
 fi
 
+# try to clean up
+if [ "$1" = "upgrade" ] && dpkg --compare-versions "$2" lt 4:25.2.1-2; then
+	if [ -d /etc/libreoffice/registry/res/ ]; then
+		rmdir /etc/libreoffice/registry/res/ || true
+	fi
+elif [ "$1" = "install" ] && [ -d /etc/libreoffice/registry/res ]; then
+	rmdir /etc/libreoffice/registry/res/ || true
+fi
+
 #DEBHELPER#
