lp#916291: failing -common postinst script
lp#916291: soft fail on registering extensions

lp#916291: add a few conflicts against -common

make extensions conflicts against libreoffice-core (<< 1:3.5~), libreoffice-common (<< 1:3.5~)

 - cherry-picked from master

Conflicts:

	changelog
	control.in

diff --git a/libreoffice-common.postinst.in b/libreoffice-common.postinst.in
--- a/libreoffice-common.postinst.in
+++ b/libreoffice-common.postinst.in
@@ -4,17 +4,6 @@ set -e
 
 #INCLUDE_SHELL_LIB#
 
-if [ "$1" = "triggered" ]; then
-	for triggername in $2; do
-		case "$triggername" in
-			# new "bundled" extensions (since 3.3)
-			"/@OODIR@/share/extensions")
-			  sync_extensions
-			;;
-		esac
-	done
-fi
-
 if [ "$1" = "configure" ]; then
 	dpkg-maintscript-helper rm_conffile "/etc/bash_completion.d/ooffice.sh" 1:3.3.0~rc4-2 libreoffice-common -- "$@"
  
@@ -29,7 +18,7 @@ if [ "$1" = "configure" ]; then
 	rmdir /etc/openoffice 2>/dev/null || true
 
 	if dpkg --compare-versions "$2" lt "1:3.3.0-3"; then
-		dpkg-trigger /@OODIR@/share/extensions
+		dpkg-trigger /@OODIR@/share/extensions || (echo "failed to trigger extension registration" && true)
 	fi
 fi
 
